server:
  port: 9000
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: project
  main:
    allow-circular-references: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true #是否启用分页合理化
  support-methods-arguments: true